### ISSUE TITLE
php7 support

### ISSUE THREAD

**Issue by arielkung** [rstgroup/php-signal-handler#7]
Hi, I like this extension as an alternative to pcntl to use it with amqp, so I tried to build it with php7 but I get errors during make:

git clone https://github.com/rstgroup/php-signal-handler && cd php-signal-handler && phpize && ./configure && make

/php-signal-handler/signal_handler.c: In function 'php_signal_callback_handler':
/php-signal-handler/signal_handler.c:141:2: error: too many arguments to function 'zend_hash_index_find'
  if(zend_hash_index_find(&SIGNAL_HANDLER_G(php_signal_table), signo, (void **) &handle) == FAILURE){
  ^
In file included from /usr/include/php/20151012/Zend/zend.h:36:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /php-signal-handler/signal_handler.c:25:
/usr/include/php/20151012/Zend/zend_hash.h:156:30: note: declared here
 ZEND_API zval* ZEND_FASTCALL zend_hash_index_find(const HashTable *ht, zend_ulong h);
                              ^
/php-signal-handler/signal_handler.c:141:89: warning: comparison between pointer and integer [enabled by default]
  if(zend_hash_index_find(&SIGNAL_HANDLER_G(php_signal_table), signo, (void **) &handle) == FAILURE){
                                                                                         ^
/php-signal-handler/signal_handler.c:152:2: warning: passing argument 6 of 'call_user_function' from incompatible pointer type [enabled by default]
  call_user_function(EG(function_table), NULL, *handle, retval, 1, &param TSRMLS_CC);
  ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /php-signal-handler/signal_handler.c:25:
/usr/include/php/20151012/Zend/zend_API.h:471:14: note: expected 'struct zval *' but argument is of type 'struct zval **'
 ZEND_API int call_user_function(HashTable *function_table, zval *object, zval *function_name, zval *retval_ptr, uint32_t param_count, zval params[]);
              ^
/php-signal-handler/signal_handler.c:154:2: warning: passing argument 1 of '_zval_ptr_dtor' from incompatible pointer type [enabled by default]
  zval_ptr_dtor(&param);
  ^
In file included from /usr/include/php/20151012/Zend/zend.h:39:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /php-signal-handler/signal_handler.c:25:
/usr/include/php/20151012/Zend/zend_variables.h:112:15: note: expected 'struct zval *' but argument is of type 'struct zval **'
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
/php-signal-handler/signal_handler.c:155:2: warning: passing argument 1 of '_zval_ptr_dtor' from incompatible pointer type [enabled by default]
  zval_ptr_dtor(&retval);
  ^
In file included from /usr/include/php/20151012/Zend/zend.h:39:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /php-signal-handler/signal_handler.c:25:
/usr/include/php/20151012/Zend/zend_variables.h:112:15: note: expected 'struct zval *' but argument is of type 'struct zval **'
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
/php-signal-handler/signal_handler.c: In function 'zif_attach_signal':
/php-signal-handler/signal_handler.c:180:3: warning: passing argument 3 of 'zend_is_callable' from incompatible pointer type [enabled by default]
   if (!zend_is_callable(handle, 0, &func_name TSRMLS_CC)) {
   ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /php-signal-handler/signal_handler.c:25:
/usr/include/php/20151012/Zend/zend_API.h:314:20: note: expected 'struct zend_string **' but argument is of type 'char **'
 ZEND_API zend_bool zend_is_callable(zval *callable, uint check_flags, zend_string **callable_name);
                    ^
/php-signal-handler/signal_handler.c:196:126: error: macro "zend_hash_index_update" passed 5 arguments, but takes just 3
  zend_hash_index_update(&SIGNAL_HANDLER_G(php_signal_table), signo, (void **) &handle, sizeof(zval *), (void **) &dest_handle);
                                                                                                                              ^
/php-signal-handler/signal_handler.c:196:2: error: 'zend_hash_index_update' undeclared (first use in this function)
  zend_hash_index_update(&SIGNAL_HANDLER_G(php_signal_table), signo, (void **) &handle, sizeof(zval *), (void **) &dest_handle);
  ^
/php-signal-handler/signal_handler.c:196:2: note: each undeclared identifier is reported only once for each function it appears in
/php-signal-handler/signal_handler.c:197:2: warning: passing argument 1 of 'zval_add_ref' from incompatible pointer type [enabled by default]
  if (dest_handle) zval_add_ref(dest_handle);
  ^
In file included from /usr/include/php/20151012/Zend/zend.h:39:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /php-signal-handler/signal_handler.c:25:
/usr/include/php/20151012/Zend/zend_variables.h:141:15: note: expected 'struct zval *' but argument is of type 'struct zval **'
 ZEND_API void zval_add_ref(zval *p);
               ^
make: *** [signal_handler.lo] Error 1

**Comment by mkaczanowski** [comment]
Hey @arielkung,
zend_hash_index_find seems to be changed in PHP7.
This plugin is not supporting php7 so far.
If you wish to make some changes please make a diff, it is very likely that I will not touch it as long as PHP7 is not more common (sorry, I do not have much time).
